=== ImNotPablosKi/DAM1202526/LENGM/2EV/BUSTRA/Repaso/pelis.dtd
<!ELEMENT pelicula (actores, director, año, duracion, sinopsis, genero*)>
<!ATTLIST pelicula id ID #REQUIRED
    titulo CDATA #REQUIRED clasificacion (PG-13|R|ATP|NC-17) "ATP">

<!ELEMENT actores (actor+)>
<!ELEMENT actor (nombre, apellidos, edad?)>
<!ATTLIST actor codigo ID #REQUIRED
    rol (extra|protagonista|secundario) #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT genero EMPTY>
<!ATTLIST genero nombre CDATA #REQUIRED>

=== ImNotPablosKi/DAM1202526/LENGM/2EV/BUSTRA/Repaso/pelis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE pelicula SYSTEM "pelis.dtd"> -->
<pelicula id="mov0001" titulo="Pascualadas" clasificacion="PG-13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pelis.xsd">
    <actores>   
        <actor codigo="a01" rol="extra">
            <nombre>Pascual</nombre>
            <apellidos>Pérez Bagán</apellidos>
            <edad>67</edad>
        </actor>
    </actores>
    <director>Pascual también</director>
    <año>2067</año>
    <duracion>190</duracion>
    <sinopsis>Volvemos al taller...</sinopsis>
    <genero nombre="SliceOfLife"></genero>
    <genero nombre="SliceOfLife"></genero>
</pelicula>
