=== ImNotPablosKi/DAM1202526/LENGM/2EV/UD6_XML/Clase/musica.dtd
<!ELEMENT tiendaMusica (disco+)>
<!ELEMENT disco (titulo, artista, año, genero, precio, canciones)>
<!ATTLIST disco id ID #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (titulo, duracion)>
<!ATTLIST cancion numero CDATA #REQUIRED>
<!ELEMENT duracion (#PCDATA)>

=== ImNotPablosKi/DAM1202526/LENGM/2EV/UD6_XML/Clase/tiendaMusica _2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendaMusica SYSTEM "musica.dtd">
<tiendaMusica>
    <disco id="D001">
        <titulo>Mayeutica</titulo>
        <artista>Robe</artista>
        <año>2021</año>
        <genero>Rock Transgresivo</genero>
        <precio>20.00</precio>
        <canciones>
            <cancion numero="1">
                <titulo>Primer Movimiento</titulo>
                <duracion>6:34</duracion>
            </cancion>
            <cancion numero="2">
                <titulo>Segundo Movimiento</titulo>
                <duracion>4:34</duracion>
            </cancion>
            <cancion numero="3">
                <titulo>Tercer Movimiento</titulo>
                <duracion>8:34</duracion>
            </cancion>
        </canciones>
    </disco>
        <disco id="D002">
        <titulo>Una Odisea Musical</titulo>
        <artista>Chasis</artista>
        <año>2001</año>
        <genero>Makina</genero>
        <precio>15.00</precio>
        <canciones>
            <cancion numero="1">
                <titulo>Fly on the wings of love</titulo>
                <duracion>5:34</duracion>
            </cancion>
            <cancion numero="2">
                <titulo>Atlantis</titulo>
                <duracion>4:34</duracion>
            </cancion>
        </canciones>
    </disco>
        <disco id="D003">
        <titulo>Trilogy</titulo>
        <artista>Pont Aeri</artista>
        <año>1999</año>
        <genero>Makina / Hardcore</genero>
        <precio>18.00</precio>
        <canciones>
            <cancion numero="1">
                <titulo>Flying Free</titulo>
                <duracion>6:34</duracion>
            </cancion>
            <cancion numero="2">
                <titulo>Reaching Dreams</titulo>
                <duracion>4:34</duracion>
            </cancion>
        </canciones>
    </disco>
</tiendaMusica>
